-- SQLite
--CREACION DE TABLAS PARA LAS CONSULTAS DE LOS EJERCICIOS.
CREATE TABLE AUTHORS(
ID INTEGER PRIMARY KEY,
NAME VARCHAR(50)
);

CREATE TABLE BOOKS(
ID INTEGER PRIMARY KEY,
NAME VARCHAR(50),
AUTHOR INTEGER REFERENCES AUTHORS(ID)
);

CREATE TABLE CUSTOMERS(
ID INTEGER PRIMARY KEY,
NAME VARCHAR(50),
E_MAIL VARCHAR(50)
);

CREATE TABLE RENTS(
ID INTEGER PRIMARY KEY,
BOOKS_ID INTEGER REFERENCES BOOKS(ID),
CUSTOMER_ID INTEGER REFERENCES CUSTOMERS(ID),
STATE VARCHAR(30)
);

--LLENANDO LAS TABLAS PARA LAS CUNSULTAS

INSERT INTO AUTHORS(ID, NAME)
VALUES
(1,	"Miguel de Cervantes"),
(2,	"Dante Alighieri"),
(3,	"Takehiko Inoue"),
(4,	"Akira Toriyama"),
(5,	"Walt Disney");

INSERT INTO BOOKS(ID, NAME, AUTHOR)
VALUES
(1,	"Don Quijote", 1),
(2,	"La Divina Comedia", 2),
(3,	"Vagabond 1-3",	3),
(4,	"Dragon Ball 1", 4),
(5,	"The Book of the 5 Rings", NULL);

INSERT INTO CUSTOMERS(ID, NAME, E_MAIL)
VALUES
(1, "John Doe", "j.doe@email.com"),
(2,	"Jane Doe",	"jane@doe.com"),
(3,	"Luke Skywalker", "darth.son@email.com");

INSERT INTO RENTS(ID, BOOKS_ID, CUSTOMER_ID, STATE)
VALUES
(1,	1,	2,	"Returned"),
(2,	2,	2,	"Returned"),
(3,	1,	1,	"On time"),
(4,	3,	1,	"On time"),
(5,	2,	2,	"Overdue");

--1 Obtenga todos los libros y sus autores (en caso de tenerlos)
SELECT BOOK.NAME, AUTHOR.NAME
FROM BOOKS AS BOOK
LEFT JOIN AUTHORS AS AUTHOR
ON BOOK.AUTHOR=AUTHOR.ID

--2 Obtenga todos los libros que no tienen autor
SELECT BOOK.NAME, AUTHOR.NAME
FROM BOOKS AS BOOK
LEFT JOIN AUTHORS AS AUTHOR
ON BOOK.AUTHOR=AUTHOR.ID WHERE AUTHOR.ID IS NULL

--Obtenga todos los autores que no tienen libros
--PARA ESTE EJERCICIO INTENTE HACERLO CON RIGHT JOIN PERO ME DA UN ERROR QUE VSCODE NO LO SOPORTA.
--SELECT BOOK.NAME, AUTHOR.NAME
--FROM BOOKS AS BOOK
--RIGHT JOIN AUTHORS AS AUTHOR
--ON BOOK.AUTHOR=AUTHOR.ID WHERE BOOK.AUTHOR IS NULL

--Los comando que use fue invertir los datos para hacer lo contrario de LEFT JOIN
--y de esa manera funcionara como RIGHT JOIN.
SELECT BOOK.NAME, AUTHOR.NAME
FROM AUTHORS AS AUTHOR
LEFT JOIN BOOKS AS BOOK
ON AUTHOR.ID=BOOK.AUTHOR WHERE BOOK.AUTHOR IS NULL

--4 Obtenga todos los libros que han sido rentados en algún momento
SELECT BOOK.NAME, RENT.STATE
FROM BOOKS AS BOOK
LEFT JOIN RENTS AS RENT
ON BOOK.ID=RENT.BOOKS_ID WHERE RENT.STATE IS NOT NULL GROUP BY NAME

--5 Obtenga todos los libros que nunca han sido rentados
SELECT BOOK.NAME, RENT.STATE
FROM BOOKS AS BOOK
LEFT JOIN RENTS AS RENT
ON BOOK.ID=RENT.BOOKS_ID WHERE RENT.STATE IS NULL

--6 Obtenga todos los clientes que nunca han rentado un libro
SELECT CUSTOMER.NAME
FROM CUSTOMERS AS CUSTOMER
LEFT JOIN RENTS AS RENT
ON CUSTOMER.ID=RENT.CUSTOMER_ID WHERE RENT.CUSTOMER_ID IS NULL

--Obtenga todos los libros que han sido rentados y están en estado “Overdue”
SELECT BOOK.NAME, RENT.STATE
FROM BOOKS AS BOOK
LEFT JOIN RENTS AS RENT
ON BOOK.ID=RENT.BOOKS_ID WHERE RENT.STATE="Overdue"
