-- COMANDOS PARA EJERCICIO NUMERO 1 DE NORMALIZACION
-- SQLite
CREATE TABLE COSTUMERS(
    ID INTEGER PRIMARY KEY NOT NULL,
    COSTUMER_NAME VARCHAR(50) NOT NULL,
    PHONE_NUMBERS VARCHAR(20) NOT NULL
    );


CREATE TABLE ADDRESS(
    ID INTEGER PRIMARY KEY NOT NULL,
    ADDRESS VARCHAR(30) NOT NULL,
    COSTUMER_ID INTEGER REFERENCES COSTUMERS (ID)
    ); 


-- SQLite
CREATE TABLE ORDERS(
    ORDER_ID INTEGER PRIMARY KEY,
    COSTUMER_ID INTEGER REFERENCES COSTUMERS(ID),
    ADDRESS_ID INTEGER REFERENCES ADDRESS(ID),
    DELIVERY_TIME VARCHAR(30) NOT NULL
    );


-- SQLite
CREATE TABLE PRODUCTS(
    ITEM_ID INTEGER PRIMARY KEY,
    ITEM_NAME VARCHAR(30) NOT NULL,
    PRICE INTEGER NOT NULL
    );


-- SQLite
CREATE TABLE ORDER_ITEMS(
    ORDER_ID INTEGER,
    ITEM_ID INTEGER,
    QUANTITY INTEGER NOT NULL,
    SPECIAL_REQUEST VARCHAR(100),
    PRIMARY KEY(ORDER_ID, ITEM_ID)
    );


--COMANDOS PARA LLENAR EL EJERCICIO  NUNMERO 1
-- SQLite
INSERT INTO COSTUMERS(ID, COSTUMER_NAME, PHONE_NUMBERS)
    VALUES
    (1, "ALICE", "123-456-7890"),
    (2, "BOB", "987-654-3210"),
    (3, "CLAIRE", "555-123-4567");


-- SQLite
INSERT INTO ADDRESS(ID, ADDRESS, COSTUMER_ID)
VALUES
(1, "123 MAIN ST", 1),
(2, "456, ELM ST", 2),
(3, "4TH AVENUE", 2),
(4, "789 OAK ST", 3),
(5, "464 GEORGIA ST", 3);


-- SQLite
INSERT INTO ORDERS(ORDER_ID, COSTUMER_ID, ADDRESS_ID, DELIVERY_TIME)
VALUES
(1, 1, 1, "6:00 PM"),
(2, 2, 2, "7:30 PM"),
(3, 2, 3, "7:30 PM"),
(4, 3, 4, "12:00 PM"),
(5, 3, 5, "5:00 PM");


-- SQLite
INSERT INTO PRODUCTS(ITEM_ID, ITEM_NAME, PRICE)
VALUES
(101, "CHEESEBURGER", 8),
(102, "FRIES", 3),
(103, "PIZZA", 12),
(105, "SALAD", 6),
(106, "WATER", 1);


-- SQLite
INSERT INTO ORDER_ITEMS(ORDER_ID, ITEM_ID, QUANTITY, SPECIAL_REQUEST)
VALUES
(1, 101, 2, "NO ONIONS"),
(1, 102, 1, "EXTRA KETCHUP"),
(2, 103, 1, "EXTRA CHEESE"),
(2, 102, 2, "NONE"),
(3, 105, 1, "NO CROUTONS"),
(4, 106, 1, "NONE");



--EJERCICIO NUMERO 2 DE NORMALIZACION
-- SQLite
CREATE TABLE MAKE(
ID INTEGER PRIMARY KEY,
NAME VARVHAR(50)
);


-- SQLite
CREATE TABLE MODEL(
ID INTEGER PRIMARY KEY,
NAME VARCHAR(30) NOT NULL,
MAKE_ID INTEGER REFERENCES MAKE (ID)
);


-- SQLite
CREATE TABLE CARS(
VIN VARCHAR(50) PRIMARY KEY,
MODEL_ID INTEGER REFERENCES MODEL (ID),
YEAR INTEGER NOT NULL,
COLOR VARCHAR(30) NOT NULL
);


-- SQLite
CREATE TABLE OWNER(
OWNER_ID INTEGER PRIMARY KEY,
NAME VARCHAR(30) NOT NULL,
PHONE VARCHAR(30) NOT NULL
);


-- SQLite
CREATE TABLE VIN_OWNER (
VIN VARCHAR(50),
OWNER_ID INTEGER,
INSURANCE_COMPANY VARCHAR(30),
INSURANCE_POLICY VARCHAR(30),
PRIMARY KEY (VIN, OWNER_ID)
);


--LLENANDO TABLA CON LOS DATOS DEL EJERCICIO 2
-- SQLite
INSERT INTO MAKE(ID, NAME)
VALUES
(1, "HONDA"),
(2, "CHEVROLET");


-- SQLite
INSERT INTO MODEL(ID, NAME, MAKE_ID)
VALUES
(1, "ACORD", 1),
(2, "CRV", 1),
(3, "VOLT", 2);


-- SQLite
INSERT INTO CARS(VIN, MODEL_ID, YEAR, COLOR)
VALUES
("1HGCM82633A", 1, 2003, "SILVER"),
("5J6RM4H79EL", 1, 2014, "BLUE"),
("1G1RA6EH1FU", 3, 2015, "RED");


-- SQLite
INSERT INTO OWNER(OWNER_ID, NAME, PHONE)
VALUES
(101, "ALICE", "123-456-7890"),
(102, "BOB", "987-654-3210"),
(103, "CLAIRE", "555-123-4567"),
(104, "DAVE", "111-222-3333");




