-- SQLite
--EJERCICIO NUMERO 2 DE NORMALIZACION MODIFICADO
CREATE TABLE MAKE(
ID INTEGER PRIMARY KEY,
NAME VARVHAR(50)
);

CREATE TABLE MODEL(
ID INTEGER PRIMARY KEY,
NAME VARCHAR(30) NOT NULL,
YEAR INTEGER NOT NULL,
MAKE_ID INTEGER REFERENCES MAKE (ID)
);

CREATE TABLE CARS(
ID INTEGER PRIMARY KEY,
VIN VARCHAR(50) NOT NULL,
MODEL_ID INTEGER REFERENCES MODEL (ID),
COLOR VARCHAR(30) NOT NULL
);

CREATE TABLE OWNER(
OWNER_ID INTEGER PRIMARY KEY,
NAME VARCHAR(30) NOT NULL,
PHONE VARCHAR(30) NOT NULL
);

CREATE TABLE INSURANCE_COMPANY(
ID INTEGER PRIMARY KEY,
NAME COMPANY VARCHAR(30) NOT NULL
);

CREATE TABLE INSURANCE_POLICY(
ID INTEGER PRIMARY KEY,
INSURANCE_POLICY VARCHAR(30) NOT NULL,
INSURANCE_ID INTEGER REFERENCES INSURANCE_COMPANY (ID)
);

CREATE TABLE CARS_OWNERS (
CAR_ID INTEGER REFERENCES CARS (ID),
OWNER_ID INTEGER REFERENCES OWNER (ID),
INSURANCE_POLICY_ID VARCHAR(30) REFERENCES INSURANCE_POLICY (ID),
PRIMARY KEY (CAR_ID, OWNER_ID, INSURANCE_POLICY_ID)
);




--LLENANDO TABLA CON LOS DATOS DEL EJERCICIO 2

DROP TABLE IF EXISTS
CARS_OWNERS;


CREATE TABLE CARS_OWNERS_2 (
CAR_ID INTEGER REFERENCES CARS (ID),
OWNER_ID INTEGER REFERENCES OWNER (ID),
INSURANCE_POLICY_ID INTEGER REFERENCES INSURANCE_POLICY (ID),
PRIMARY KEY (CAR_ID, OWNER_ID, INSURANCE_POLICY_ID)
);


INSERT INTO MAKE(ID, NAME)
VALUES
(1, "HONDA"),
(2, "CHEVROLET");


INSERT INTO MODEL(ID, NAME, YEAR, MAKE_ID)
VALUES
(1, "ACORD", 2003, 1),
(2, "CRV", 2014, 1),
(3, "VOLT", 2015, 2);


INSERT INTO CARS(ID, VIN, MODEL_ID, COLOR)
VALUES
(1,	"1HGCM82633A", 1, "SILVER"), 
(2, "5J6RM4H79EL", 2, "BLUE"),
(3, "1G1RA6EH1FU", 3, "RED");


INSERT INTO INSURANCE_COMPANY(ID, NAME)
VALUES
(1, "ABC INSURANCE"),
(2,	"XYZ INSURANCE"),
(3, "DEF INSURANCE"),
(4,	"GHI INSURANCE");


INSERT INTO INSURANCE_POLICY(ID, INSURANCE_POLICY, INSURANCE_ID)
VALUES
(1,	"FIRE AND THEFT", 1),
(2,	"FULL COVER", 2),
(3,	"COLLISION",3),
(4, "BASIC LEGAL", 4);


INSERT INTO OWNER(OWNER_ID, NAME, PHONE)
VALUES
(101, "ALICE", "123-456-7890"),
(102, "BOB", "987-654-3210"),
(103, "CLAIRE", "555-123-4567"),
(104, "DAVE", "111-222-3333");


INSERT INTO CARS_OWNERS_2(CAR_ID, OWNER_ID, INSURANCE_POLICY_ID)
VALUES
(1,	101, 1),
(1,	102, 2),
(2,	103, 3),
(3,	104, 4);
