-- 1. CREACIÓN DE TABLAS BASE
CREATE TABLE PRODUCTS (
ID INTEGER PRIMARY KEY,
CODE VARCHAR(15) NOT NULL,
NAME VARCHAR(25) NOT NULL,
PRICE SMALLINT DEFAULT 0,
DATE VARCHAR(15) NOT NULL CHECK(DATE LIKE "____-__-__"),
BRAND VARCHAR(25) NOT NULL
);

CREATE TABLE INVOICES(
ID INTEGER PRIMARY KEY,
N VARCHAR(15)NOT NULL,
DATE VARCHAR(15) NOT NULL CHECK(DATE LIKE"____-__-__"),
E_MAIL VARCHAR(30) NOT NULL,
TOTAL INTEGER NOT NULL
);

CREATE TABLE INVOICE_DETAILS(
ID INTEGER PRIMARY KEY,
QUANTITY_PURCHASED SMALLINT NOT NULL,
TOTAL_AMOUNT INTEGER NOT NULL,
PRODUCT_ID INTEGER REFERENCES PRODUCTS (ID),
INVOICE_ID INTEGER REFERENCES INVOICES (ID)
);

CREATE TABLE USERS (
ID INTEGER PRIMARY KEY,
E_MAIL VARCHAR(30) NOT NULL
);

CREATE TABLE SHOPPING_CART (
ID INTEGER PRIMARY KEY,
PRODUCT_ID INTEGER REFERENCES PRODUCTS(ID),
USER_ID INTEGER REFERENCES USERS (ID),
QUANTITY SMALLINT NOT NULL
);

CREATE TABLE REVIEWS (
ID INTEGER PRIMARY KEY,
P_CODE VARCHAR(20) NOT NULL,
COMMENT VARCHAR(50),
QUALIFICATION VARCHAR(5) NOT NULL,
DATE VARCHAR(10) CHECK (DATE LIKE "____-__-__"),
PRODUCT_ID INTEGER REFERENCES PRODUCTS(ID),
USER_ID INTEGER REFERENCES USERS(ID)
);

CREATE TABLE PAYMENT_METHOD (
ID INTEGER PRIMARY KEY,
METHOD_TYPE VARCHAR(25) NOT NULL
);

-- 2. TABLA DE CATEGORÍAS (Requerida por ejercicios posteriores)
CREATE TABLE CATEGORIES (
ID INTEGER PRIMARY KEY,
NAME VARCHAR(25) UNIQUE NOT NULL,
DESCRIPTION VARCHAR(50) NOT NULL
);

-- 3. ALTERACIONES (Agregar columnas)
ALTER TABLE USERS ADD FULL_NAME VARCHAR(25);
ALTER TABLE USERS ADD R_DATE VARCHAR(25);

ALTER TABLE INVOICES ADD USER_ID INTEGER REFERENCES USERS(ID);
ALTER TABLE INVOICES ADD PAYMENT_MET_ID INTEGER REFERENCES PAYMENT_METHOD(ID);

-- ALTERACIONES DE PRODUCTOS (Requeridas por ejercicios posteriores)
ALTER TABLE PRODUCTS ADD CATEGORY_ID INTEGER REFERENCES CATEGORIES(ID);
ALTER TABLE PRODUCTS ADD QUANTITY INTEGER;

-- CREACION DE LAS DOS COLUMNAS PARA CUMPLIR CON LOS CAMBIOS SOLICITADOS.
ALTER TABLE INVOICES
ADD EMPLOYEE_CODE SMALLINT;

ALTER TABLE INVOICES
ADD C_PHONE_NUMBER VARCHAR(15);