-- SQLite
--EJRCICIO 1 EMPLOYEE AND PROJECTS 

CREATE TABLE EMPLOYEE(
ID INTEGER PRIMARY KEY,
EMPLOYEE_NAME VARCHAR(50) NOT NULL
);

CREATE TABLE DEPARTMENT(
ID INTEGER PRIMARY KEY,
DEPARTMENT VARCHAR(30) NOT NULL,
DEPARTMENT_PHONE VARCHAR(20) NOT NULL
);

CREATE TABLE PROJECT(
PROJECT_ID VARCHAR(20) PRIMARY KEY,
PROJECT_NAME VARCHAR(40) NOT NULL,
PROJECT_BUDGET INTEGER NOT NULL
);

CREATE TABLE EMPLOYEE_PROJECT(
EMPLOYEE_ID INTEGER REFERENCES EMPLOYEE(ID),
DEPARTMENT_ID INTEGER REFERENCES DEPARTMENT (ID),
PROJECT_ID VARCHAR(20) REFERENCES PROJECT(PROJECT_ID)
);

INSERT INTO EMPLOYEE(ID, EMPLOYEE_NAME)
VALUES
(201, "ANA RIVERA"),
(202, "LUIS MENDEZ");

INSERT INTO DEPARTMENT(ID, DEPARTMENT, DEPARTMENT_PHONE)
VALUES
(1, "IT", "2222-2222"),
(2, "MAARKETING", "1111-1111");

INSERT INTO PROJECT(PROJECT_ID, PROJECT_NAME, PROJECT_BUDGET)
VALUES
("P001", "WEB APP", 50000),
("P002", "API REST",    25000),
("P003", "CAMPAÑA TV", 30000);

INSERT INTO EMPLOYEE_PROJECT(EMPLOYEE_ID, DEPARTMENT_ID, PROJECT_ID)
VALUES
(201, 1, "P001"),
(201, 1, "P002"),
(202, 2, "P003");




-- EJERCICIO 2 Normalización de Registro de Clases
CREATE TABLE STUDENT(
STUDENT_ID INTEGER PRIMARY KEY,
STUDENT_NAME VARCHAR(40) NOT NULL
);

CREATE TABLE INSTRUCTOR(
ID INTEGER PRIMARY KEY,
INSTRUCTOR_NAME VARCHAR(40) NOT NULL,
INSTRUCTOR_EMAIL VARCHAR(30) NOT NULL
);

CREATE TABLE COURSE(
COURSE_CODE VARCHAR(30) PRIMARY KEY,
CURSE_NAME VARCHAR(50) NOT NULL,
INSTRUCTOR_ID INTEGER REFERENCES INSTRUCTOR (ID)
);

CREATE TABLE COURSE_REGISTRATION(
STUDENT_ID INTEGER REFERENCES STUDENT(STUDENT_ID),
COURSE_CODE VARCHAR(30) REFERENCES COURSE(COURSE_CODE),
PRIMARY KEY(STUDENT_ID, COURSE_CODE)
);

INSERT INTO STUDENT(STUDENT_ID, STUDENT_NAME)
VALUES
(301, "MARCOS GOMEZ"),
(302, "CARLA RUIZ");

INSERT INTO INSTRUCTOR(ID, INSTRUCTOR_NAME, INSTRUCTOR_EMAIL)
VALUES
(1, "JUAN PEREZ", "juan@uni.edu"),
(2, "LAURA ROJAS", "laura@uni.edu");

INSERT INTO COURSE(COURSE_CODE, CURSE_NAME, INSTRUCTOR_ID)
VALUES
("CS101", "PYTHON I", 1),
("CS102", "PYTHON II", 2);

INSERT INTO COURSE_REGISTRATION(STUDENT_ID, COURSE_CODE)
VALUES
(301, "CS101"),
(301, "CS102"),
(302, "CS101");




--EJERCICIO 3 Normalización de Hospital y Citas Médicas

CREATE TABLE PATIENT(
ID INTEGER PRIMARY KEY,
PATIENT_NAME VARCHAR(40) NOT NULL,
PATIENT_PHONE VARCHAR(20)
);

CREATE TABLE DOCTOR(
ID INTEGER PRIMARY KEY,
DOCTOR_NAME VARCHAR(40) NOT NULL,
SPECIALTY VARCHAR(50) NOT NULL
);

CREATE TABLE APPOINTMENT(
APPOINTMENT_ID VARCHAR(30) PRIMARY KEY,
DATE VARCHAR(20) NOT NULL,
TIME VARCHAR(20) NOT NULL
);

CREATE TABLE CITAS_MEDICAS(
PATIENT_ID INTEGER REFERENCES PATIENT(ID),
APPOINTMENT_ID VARCHAR(30) REFERENCES APPOINTMENT(APPOINTMENT_ID),
DOCTOR_ID INTEGER REFERENCES DOCTOR(ID),
PRIMARY KEY(PATIENT_ID, APPOINTMENT_ID, DOCTOR_ID)
);


INSERT INTO PATIENT(ID, PATIENT_NAME, PATIENT_PHONE)
VALUES
(1, "DIANA VARGAS", "8888-1111"),
(2, "EDWIN MORA", "8999-2222");

INSERT INTO DOCTOR(ID, DOCTOR_NAME, SPECIALTY)
VALUES
(1, "DR. SOTO", "PEDIATRA"),
(2, "DR. MORA", "CARDIOLOGA");


INSERT INTO APPOINTMENT(APPOINTMENT_ID, DATE, TIME)
VALUES
("A01",	"2024-08-01", "10:00 AM"),
("A02",	"2024-08-10", "10:00 AM"),
("A03",	"2024-08-05", "01:00 PM");

INSERT INTO CITAS_MEDICAS(PATIENT_ID, APPOINTMENT_ID, DOCTOR_ID)
VALUES
(1, "A01", 1),
(1, "A02", 1),
(2, "A03", 2);



--1FN En todos los ejercicios aprecia que en la tabla original de cada uno de ellos no existen datos multiples 
--    en una sola celda asi que pasan la primera forma normal.

--2FN En todas las tablas de ejercicio, separamos los datos evitando toda dependencia  parcial  
--    y los agrupamos en tablas donde cada dato dependan de la clave primaria.

-- 3FN se agruparon los datos representados como  FK en las tablas cruz de cada ejercicio  (employee project,
--     registro de clases, citas medicas) para que cada dato dependa de la clave primaria compuesta evitando dependencia tranciva.  